DROP TABLE IF EXISTS "Kisi";
CREATE TABLE "Kisi" ("Id" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL , "Ad" TEXT, "Soyad" TEXT, "SilindiMi" BOOL NOT NULL );
INSERT INTO "Kisi" VALUES(1,'Mahmut','Gundogdu',0);
INSERT INTO "Kisi" VALUES(1,'John','Doe',1);
